In [3]:
import pickle
from sklearn.decomposition import PCA

ClassNames = ['airport', 'bus', 'metro', 'metro_station', 'park', 'public_square',
 'shopping_mall', 'street_pedestrian', 'street_traffic', 'tram']

In [4]:
# Load in pckl files of logits and yvals
with open('/work/contractors/jtaylor/acoustic_scene_classification/demo/twostage_embeddings.pckl', 'rb') as f:
    two_stage_embeddings, two_stage_y = pickle.load(f)
    
pca3 = PCA(3)
pca3.fit(two_stage_embeddings)
embeddings3 = pca3.transform(two_stage_embeddings)
print(embeddings3)
    

[[ 0.20173562  1.4312828  -0.14845628]
 [ 0.35758138  0.89702064  0.1425996 ]
 [ 0.32068294  1.0939369   0.23514386]
 ...
 [-1.4473528  -0.91588306  0.01410972]
 [-0.7841657  -0.740765    0.56385636]
 [-1.365814   -0.66108775 -0.08615839]]


In [ ]:
data = embeddings3
ids = two_stage_y
# creating 3d plot using matplotlib 
# in python
 
# for creating a responsive plot
%matplotlib widget
 
# importing required libraries
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
 
indices = np.random.choice(len(data), size=1000, replace=False)

# Extract x, y, and z coordinates from the sampled indices
x = data[indices, 0]
y = data[indices, 1]
z = data[indices, 2]

# Extract IDs for the sampled indices
sampled_ids = [ids[i] for i in indices]

# Map IDs to colors using the colormap
color_list = ["tab:blue","tab:orange","tab:green","tab:red","tab:purple","tab:brown","tab:pink","tab:gray","tab:olive","tab:cyan"]
colors = [color_list[i] for i in sampled_ids]

# creating figure
fig = plt.figure()
ax = Axes3D(fig)
 
# creating the plot 
unique_ids = np.unique(sampled_ids)
print(unique_ids)

for i, unique_id in enumerate(unique_ids):
    # Select data points for the current ID
    id_mask = sampled_ids == unique_id
    x_id = x[id_mask]
    y_id = y[id_mask]
    z_id = z[id_mask]

    # Plot the data points with color-coding
    print(color_list[unique_id])
    colors_id = [color for color, mask in zip(colors, id_mask) if mask]
    print(colors_id)
    ax.scatter(x_id, y_id, z_id, c=colors_id, label=ClassNames[unique_id], alpha=0.3)

# setting title and labels
ax.set_title("3D plot")
ax.set_xlabel('x-axis')
ax.set_ylabel('y-axis')
ax.set_zlabel('z-axis')
 
# displaying the plot
plt.show()